<html>
  <head>
    <title>ffmvc Example View</title>
  </head>

  <body>
    <h1>Example View</h1>
    <ul>
      <li>Request URL: <code><?=$requestUrl;?></code></li>
      <li>Controller: <code><?=$controllerName;?></code></li>
      <li>Method: <code><?=$methodName;?></code></li>
    </ul>

    <p>Generated by ffmvc <?=ffmvc::VERSION;?>.
  </body>
</html>
